vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        service_image:
            uri_prefix: /imgs/services
            upload_destination: '%kernel.project_dir%/public/imgs/services'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
